### ISSUE TITLE
CTE's are broken in SQLiteStudio, but not within SQLite

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4669]
### Details
When I use nested CTE's I get a syntax error in SQLiteStudio (version 3.4.3).  When I run the same query on the SQLite command line, it works without any issues.

### Steps to reproduce
Please copy and paste this set of queries into SQLiteStudio.  You will get the error "Error while executing SQL query on database 'Test': near ")": syntax error"

create table A (RecordID int, RecordName text);

insert into A values (65,"A"), (66,"B"), (67,"C"), (68,"D"),(69,"E"), (70,"F"),(71,"G"), (72,"H"),(73,"I"), (74,"J");

with IDfromA as (
select distinct RecordID from A),

NameFromA as (
select distinct RecordName from A)

select RecordID, RecordName from IDfromA, NamefromA;

Now, if you type these queries directly into the SQLite command line, it works perfectly fine, producing the expected output.

### Operating system
Windows 11 Home, 22H2

### SQLiteStudio version
3.4.3

**Comment by balajiramanathan** [comment]
I think this got broken very recently (either just in 3.4.3 or in 3.4.2).  Previous versions of SQLiteStudio work fine with CTE's.

**Comment by dkeith68** [comment]
Displaying a View's results shows same syntax error.  Apologies if "CTE" == View

**Comment by pawelsalawa** [comment]
No, CTE is not the same as View, but if your View uses (queries) with CTE, then error in CTE will impact it.

**Comment by bderider100** [comment]
I can confirm that one has to go back to 3.4.1 for with common table expression queries/views to work.

**Comment by pawelsalawa** [comment]
Fixed together with #4676

**Comment by balajiramanathan** [comment]
Since the windows builds are still failing, and 3.4.4 has not been released, how can I get a version of sqlitestudio with the fix?  Thank you.

**Comment by pawelsalawa** [comment]
I'm working on the builds, so you will be able to get the nightly build either this night or sometime soon.

Still I recommend you to wait for the #4685 to be fixed, as it is also somewhat related to this bug. I'm working on that one too, so it should be fixed in the nightly shortly.

**Comment by balajiramanathan** [comment]
OK, great.  Thank you.
