### ISSUE TITLE
`deterministic` function property is not persisted

### ISSUE THREAD

**Issue by tuffnatty** [pawelsalawa/sqlitestudio#4848]
### Details
The function editor allows to set the `deterministic` property, but it does not persist in the settings file.

### Steps to reproduce
Edit, save, restart, check.

### Operating system
any

### SQLiteStudio version
3.4.4

**Comment by tuffnatty** [comment]
Fixed with #4817.

**Comment by githubuser181226** [comment]
Hello.
Please, re-open, because `deterministic` in latest 3.4.20 version still gets turned off (for every single function) on program restart.
It does not persist between sessions.
If set, then function is used somewhere in the database, after the restart, the program fails to even open the database because of an error.
